{
  "formatVersion": "1.1",
  "component": {
    "group": "com.minminaya",
    "module": "exposure_plugin",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "exposure_plugin-0.0.1.jar",
          "url": "exposure_plugin-0.0.1.jar",
          "size": 4138,
          "sha512": "6f47a2e36dcb620703b25cd3b642d254eb37f1ce871fefd5d198f3eb59cba8f5fdb37a6bb4ec6e005d7123da2980fe86977a0333045b2e4d0015d5d2beae5a6b",
          "sha256": "952f43844f0efae50b32a6556641e09d9eb0c79b8398eaf22ad5d54f384860ba",
          "sha1": "b395bef194e0e862ef0a91d94b2f85509344b5c5",
          "md5": "f2be24a4f753f0834284252bd7888df0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "com.didiglobal.booster",
          "module": "booster-api",
          "version": {
            "requires": "4.5.3"
          }
        },
        {
          "group": "com.didiglobal.booster",
          "module": "booster-transform-asm",
          "version": {
            "requires": "4.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "exposure_plugin-0.0.1.jar",
          "url": "exposure_plugin-0.0.1.jar",
          "size": 4138,
          "sha512": "6f47a2e36dcb620703b25cd3b642d254eb37f1ce871fefd5d198f3eb59cba8f5fdb37a6bb4ec6e005d7123da2980fe86977a0333045b2e4d0015d5d2beae5a6b",
          "sha256": "952f43844f0efae50b32a6556641e09d9eb0c79b8398eaf22ad5d54f384860ba",
          "sha1": "b395bef194e0e862ef0a91d94b2f85509344b5c5",
          "md5": "f2be24a4f753f0834284252bd7888df0"
        }
      ]
    }
  ]
}
